### ISSUE TITLE
Minions bug: Sacral vault and Meat thresher

### ISSUE THREAD

**Issue by MrGraveRisen** [pumpi/troop-creator#66]
Minions:

The meat thresher should be limited to pig casters and the Sacral vault should be limited to Gator casters, yet all casters can pick both battle engines

**Comment by pumpi** [comment]
The base problem is that minions can not play without an contract but the troop creator dont need it to start. In the contracts then only can select available models

**Comment by chrisdopuch** [comment]
I think it is a confusing user experience to have to select the contract from the theme list dropdown. It took me a few minutes to figure this out :laughing: 

An easy solution would be to change the dropdown text from `no tier selected...` to `no tier/contract selected...`

Otherwise, I think a more robust solution would be to add an additional drop down menu which only appears on the Minion or Mercenary page to select the contract. This avoids the additional confusion of seeing the four stars at the top for indicating which tier of a theme list you are using (since this information is not needed for contracts).

**Comment by pumpi** [comment]
this is a good idear. i whil change something so make the user experience better. I think that an good way is tho pre select an contract if an user select minion or merchs

**Comment by Hjard** [comment]
Probably obsolete now?

**Comment by pumpi** [comment]
no contracts in MKIII
